---
deployment:
  tasks:
    # Set the deployment path to public_html
    - export DEPLOYPATH=/home/zaho/public_html/
    
    # Copy only the contents of the out/ folder to public_html
    - /bin/cp -R /home/zaho/repositories/zaho-web/out/* $DEPLOYPATH
    
    # Remove any git metadata from public_html
    - /bin/rm -rf $DEPLOYPATH/.git
